task: MultiMNIST
synthesizer: Summation
continuation_model_path: "/scratch/hpc-lco-plessl-hpc/dvoth/backdoors101/runs/trained_models/clean_sgd.tar"
distributed: True

batch_size: 1
test_batch_size: 100
val_batch_size: 100
lr: 0.005
momentum: 0.9
decay: 0.0005
epochs: 10
save_on_epochs: [0, 1]
optimizer: SGD
log_interval: 300
scheduler: False

poisoning_proportion: 0.8
backdoor_label: 8
backdoor: False
backdoor_dynamic_position: False

loss_balance: MGDA
mgda_normalize: loss

save_model: True
log: True
tb: False

continuation: False
max_continuation_iterations: 100
plot_continuation_on_iteration: 4
continuation_checkpoints_at: 4
calibration: False
calibration_iterations: 2000
stop_at: 0.001
predictor_steps: 16
predictor_lr: 0.0001
corrector_steps: 32
corrector_lr: 0.0001
other_direction: False
both_directions: False
track_training: True
count_passes: True

transform_train: True


loss_tasks:
  - backdoor
  - normal
#  - neural_cleanse
#  - sentinet_evasion



#poison_images_test:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588
#
#poison_images:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588